import React from "react";

const Spinner = () => {
	return (
		<div className="spinner-wrap">
			<div className="loadingio-spinner-gear-hjndyeejhfj">
				<div className="ldio-5zvj2sm75l6">
					<div>
						<div></div>
						<div></div>
						<div></div>
						<div></div>
						<div></div>
						<div></div>
					</div>
				</div>
			</div>
			<style jsx>
				{`
					@keyframes ldio-5zvj2sm75l6 {
						0% {
							transform: rotate(0deg);
						}
						50% {
							transform: rotate(22.5deg);
						}
						100% {
							transform: rotate(45deg);
						}
					}
					.spinner-wrap {
						display: flex;
						justify-content: center;
						align-items: center;
						width: 100%;
						height: 470px;
					}
					.ldio-5zvj2sm75l6 > div {
						transform-origin: 50.5px 50.5px;
						animation: ldio-5zvj2sm75l6 0.2s infinite linear;
					}
					.ldio-5zvj2sm75l6 > div div {
						position: absolute;
						width: 11.11px;
						height: 80.8px;
						background: #608d98;
						left: 50.5px;
						top: 50.5px;
						transform: translate(-50%, -50%);
					}
					.ldio-5zvj2sm75l6 > div div:nth-child(1) {
						width: 64.64px;
						height: 64.64px;
						border-radius: 50%;
					}
					.ldio-5zvj2sm75l6 > div div:nth-child(6) {
						width: 30.3px;
						height: 30.3px;
						background: #ffffff;
						border-radius: 50%;
					}
					.ldio-5zvj2sm75l6 > div div:nth-child(3) {
						transform: translate(-50%, -50%) rotate(45deg);
					}
					.ldio-5zvj2sm75l6 > div div:nth-child(4) {
						transform: translate(-50%, -50%) rotate(90deg);
					}
					.ldio-5zvj2sm75l6 > div div:nth-child(5) {
						transform: translate(-50%, -50%) rotate(135deg);
					}
					.loadingio-spinner-gear-hjndyeejhfj {
						width: 101px;
						height: 101px;
						display: inline-block;
						overflow: hidden;
						background: #ffffff;
					}
					.ldio-5zvj2sm75l6 {
						width: 100%;
						height: 100%;
						position: relative;
						transform: translateZ(0) scale(1);
						backface-visibility: hidden;
						transform-origin: 0 0; /* see note above */
					}
					.ldio-5zvj2sm75l6 div {
						box-sizing: content-box;
					}
					/* generated by https://loading.io/ */
				`}
			</style>
		</div>
	);
};

export default Spinner;
