import React from "react";

const SpinnerMini = () => {
	return (
		<div className="spinner-wrap">
			<div className="loadingio-spinner-gear-w4yoy6frf6g">
				<div className="ldio-sydozsi1p0g">
					<div>
						<div></div>
						<div></div>
						<div></div>
						<div></div>
						<div></div>
						<div></div>
					</div>
				</div>
			</div>

			<style jsx>
				{`
					@keyframes ldio-sydozsi1p0g {
						0% {
							transform: rotate(0deg);
						}
						50% {
							transform: rotate(22.5deg);
						}
						100% {
							transform: rotate(45deg);
						}
					}
					.ldio-sydozsi1p0g > div {
						transform-origin: 50px 50px;
						animation: ldio-sydozsi1p0g 0.2s infinite linear;
					}
					.ldio-sydozsi1p0g > div div {
						position: absolute;
						width: 11px;
						height: 78px;
						background: #608d98;
						left: 50px;
						top: 50px;
						transform: translate(-50%, -50%);
					}
					.ldio-sydozsi1p0g > div div:nth-child(1) {
						width: 62px;
						height: 62px;
						border-radius: 50%;
					}
					.ldio-sydozsi1p0g > div div:nth-child(6) {
						width: 30px;
						height: 30px;
						background: #ffffff;
						border-radius: 50%;
					}
					.ldio-sydozsi1p0g > div div:nth-child(3) {
						transform: translate(-50%, -50%) rotate(45deg);
					}
					.ldio-sydozsi1p0g > div div:nth-child(4) {
						transform: translate(-50%, -50%) rotate(90deg);
					}
					.ldio-sydozsi1p0g > div div:nth-child(5) {
						transform: translate(-50%, -50%) rotate(135deg);
					}
					.loadingio-spinner-gear-w4yoy6frf6g {
						width: 51px;
						height: 51px;
						display: inline-block;
						overflow: hidden;
						background: #ffffff;
					}
					.ldio-sydozsi1p0g {
						width: 100%;
						height: 100%;
						position: relative;
						transform: translateZ(0) scale(0.51);
						backface-visibility: hidden;
						transform-origin: 0 0; /* see note above */
					}
					.ldio-sydozsi1p0g div {
						box-sizing: content-box;
					}
					/* generated by https://loading.io/ */
				`}
			</style>
		</div>
	);
};

export default SpinnerMini;
